[package]
name = "rusty-image"
version = "0.1.0"
authors = ["Rudi B. Svartveit <rudsvar@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.22.3"
indicatif = "0.13.0"
structopt = "0.3.5"
termion = "1.5.4"
log = "0.4.8"
stderrlog = "0.4.3"
